# 应用服务 WEB 访问端口
server:
  port: 9096
  servlet:
    context-path: /adSystem

spring:
  application:
    name: ad-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smma?zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  redis:
    database: 0
    host: 10.192.16.210
    port: 7019
    password: 3xJJAf8U


logging:
  level:
    root: info
  config: classpath:logback.xml


swagger:
  enable: true